#ifndef GUARD_CONSTANTS_MAP_GROUPS_H
#define GUARD_CONSTANTS_MAP_GROUPS_H

// Placeholder for map group and map id definitions normally generated by tools.
// Required for preprocessing headers on non-GBA platforms.

#endif // GUARD_CONSTANTS_MAP_GROUPS_H
